# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-web-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: crater-web-backend
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/web-backend/configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-web-backend
  template:
    metadata:
      labels:
        app: crater-web-backend
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.web.migrate.createMigrationJob }}
      initContainers:
        - name: migration
          image: {{ .Values.web.backend.image.repository }}:{{ .Values.web.backend.image.tag }}
          imagePullPolicy: {{ .Values.web.backend.image.pullPolicy }}
          command: ["./migrate"]
          env:
            - name: CRATER_ADMIN_USERNAME
              value: {{ .Values.web.migrate.admin.username }}
            - name: CRATER_ADMIN_PASSWORD
              value: {{ .Values.web.migrate.admin.password }}
          volumeMounts:
            - name: backend-conf
              mountPath: /etc/config/config.yaml
              subPath: config.yaml
      {{- end }}
      containers:
        - name: crater-web-backend-container
          image: {{ .Values.web.backend.image.repository }}:{{ .Values.web.backend.image.tag }}
          imagePullPolicy: {{ .Values.web.backend.image.pullPolicy }}
          command:
            - /controller
            - --config-file=/etc/config/config.yaml
          volumeMounts:
            - name: backend-conf
              mountPath: /etc/config/config.yaml
              subPath: config.yaml
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8088
              name: docusaurus
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 5
      serviceAccountName: crater-web-backend
      volumes:
        - name: backend-conf
          configMap:
            name: backend-config
            items:
              - key: config.yaml
                path: config.yaml
      nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 8 }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
